### PR TITLE
Print sub-schemas errors if failed to validate.

### PR DESCRIPTION
**Pull request by kamilbrozyna**
https://jiracommercial.flir.com/browse/CORTEX-616

Added additional messaging to easier debug cases when no sub-schemas succeed to validate.

### CODE REVIEW

**Comment by jmuncaster** [comment]
Can you please compare your changes with the latest version of pboettch/json-schema-validator/  ?

If the current version of pboettch/json-schema-validator would achieve the same thing as this PR, I would recommend simply updating the version.

If the current version of pboettch/json-schema-validator does not address your concerns, then we can update it here.

**Review by mlarocque-oti — APPROVED** [review]
Looks good to me. Make sure to address comment from @jmuncaster .
Also, it will need to be propagated through the other module up to cortex... A lot of PR :-).

**Comment by kamilbrozyna** [comment]
> Can you please compare your changes with the latest version of pboettch/json-schema-validator/ ?
> 
> If the current version of pboettch/json-schema-validator would achieve the same thing as this PR, I would recommend simply updating the version.
> 
> If the current version of pboettch/json-schema-validator does not address your concerns, then we can update it here.

I checked that already. They have a draft PR to find the most matching sub-schema to print the error, but not yet finished:
[ [DRAFT] Provide richer error info for logical combination schemas #67 ](https://github.com/pboettch/json-schema-validator/pull/67)

**Comment by rmend016** [comment]
Thank you @kamilbrozyna-digica !

**Pull request merged**
